- components/Header.js
- components/Loading.js
- firebase.js
- lib/db.js
- next-env.d.ts
- package.json
- pages/_app.tsx
- pages/index.tsx
- pages/login.js
This commit adds login functionality using email and password.
Note: all pages are mocks and waiting for design implementation; however, login functionality works.
Installed libraries:
- npm install --save styled-components: not really needed with Tailwind;
- npm install @mui/material
- npm install @emotion/react
- npm install @emotion/styled
- npm i firebase: to use Firebase
- npm install react-firebase-hooks: for authentications and various Firebase hooks
- npm i better-react-spinkit: to add waiting spin logo
- npm install email-validator: to validate user's email
> Add login functionalities with no logout on refresh using Firebase.

- components/Header/Header.tsx
- components/Header/LogoutButton.tsx
- components/Header/NavLinks.tsx
- components/Header/SearchBar.tsx
- components/Header/SearchBarButton.tsx
- components/Header/SettingsButton.tsx
- components/Header/ToggleTheme.tsx
- components/Header/UserDropdown.tsx
Handles what we discussed in discord. Waiting on updated mobile design to decide how to handle large search bar.
> fix search form resize & move user tools into dropdown

- components/FeedAPI.js
- components/InputBoxAPI.js
- components/PostAPI.js
- components/PostsAPI.js
- firebase.js
- next.config.js
- pages/index.tsx
- styles/globals.css
Added server-side rendering for posts.
NOTE:
All the following components are MOCK components used to push and visualize some results:
- FeedAPI
- InputBoxAPI
- PostsAPI
- PostAPI
I also added a style in globals.css.
Feel free to remove/replace/modify them as you need and w.r.t. the design.
Libraries to install:
- npm install @heroicons/react (I used some TailwindCss icons)
- npm i react-firebase-hooks (this may have been already installed for auth - double check)
> Add publish and pull basic posts with image.

- components/Comment.js
- components/CommentsPanel.js
- components/Feed/PostAPI.js
- components/Feed/PostsAPI.js
- lib/db.js
- package.json
- pages/comments/[id].js
This commit adds the comments page and real-time APIs to add comments, like comments, etc. The UI is just a mock while the DB queries are working.
New libraries:
- npm install uuid: to get a unique id for each comment (required, for example, to delete it)
- npm install tailwind-scrollbar-hide: not used yet but installed
- npm i safe-json-stringify: not used but installed
> Federico/dw 54/add comments apis

- components/Comment.js
- components/Feed/NextPostForm.tsx
- components/Feed/PostAPI.js
- styles/globals.css
APIs for voting, adding comparison media, and doing so the DB side is consistent and there are no race conditions.
> Add voting APIs

- components/Comment.js
- components/CommentsPanel.js
- components/Feed/PostAPI.js
- components/Feed/PostCard.tsx
- components/Feed/PostsAPI.js
Added delete post functionality -> needs proper UI and modal to ask the user if he/she is sure he/she wants to delete the post.
Added delete comment structure -> needs proper ids once the comments are available.
> Add delete post and comment APIs

- atoms/userProfile.js
- components/Feed/PostCard.tsx
- components/ProfileSettings.js
- lib/db.js
- lib/user.js
- next.config.js
- package.json
- pages/_app.tsx
- pages/feed/[id].js
- pages/index.tsx
- pages/login.js
Changes in this review:
- Added user profile settings API (mock UI): this is done only the first time the user logs in
- Added profiles collection in the DB
- Re-route the feed under /feed/[user_uid]
- Fixed a bug that wasn't deleting the posts from the user's profile in the back-end
Libraries installed:
- npm i recoil: to create global states available to all subcomponents. This will be used to have userProfile available everywhere (currently not used)
- npm i lodash: for some utility functions
- npm i crypto-random-string: to generate random strings used to generate random usernames
- npm i unique-names-generator: to generate random usernames
What it is needed:
- UI design for profile settings: currently using a mock UI
- ability to upload a profile picture and store it into the DB: …
> Add profile setup, change rerouting and fixed delete posts

- components/Feed/NewPostForm.tsx
- components/Feed/PostCard.tsx
- Moved the uploads to sequential upload plus - I believe this is the actual fix, definitely it was a bug - use a unique name for each media stored in Firebase Storage under the folder names as the post id.
- Add delete of media from Firebase Storage when deleting a post.
> Fix media upload to Firebase

- components/Feed/FeedAPI.tsx
- components/Layout.tsx
- pages/index.tsx
- tailwind.config.js
Layout scrollbar removed by adding divs to layout and following css:
- min-h-screen max-h-screen overflow-y-hidden
- sticky (Header)
> Hide overflow scrollbar

- components/Utils/Button.tsx
- pages/comments/[id].tsx
- styles/feed.js
Added Back button sticky.
Don't know how to remove the blur from the top caused by the header shadow.
> Modified Back button on comments to make it sticky

- components/Feed/FeedAPI.tsx
- components/Feed/Post/PostsAPI.tsx
- pages/comments/[id].tsx
- pages/feed/[id].js
- styles/feed.js
Fixes back button and feed toolbar to be sticky.
> fix feed/comment toolbars to top

- components/Feed/Post/PostVotingMechanism.tsx
- styles/feed.js
- Changed style for Vote image feed items and resolve the issue.
> fixed issue with feed vote images.

- .gitignore
- components/Feed/Comments/CommentEngagementBar.tsx
- components/Feed/Forms/NewPostForm.tsx
- components/Feed/Post/PostEngagementBar.tsx
- components/Feed/Post/PostHeader.tsx
- components/Feed/Post/PostVotingMechanism.tsx
- components/Feed/Post/PostsAPI.tsx
- components/Feed/Replies/ReplyEngagementBar.tsx
- components/Login/UserProfileForm.tsx
- components/Utils/Button.tsx
- styles/feed.js
- utils/helpers/common.ts
- utils/types/global.ts
NOT HOOKED
NOT TESTED
Will update this PR after initial review.
> Add initial function to create and update user profile.

- components/Feed/Post/PostEngagementBar.tsx
- lib/userHelper.ts
Solution description [here](https://stackoverflow.com/questions/50653608/firebase-invalid-document-reference-document-references-must-have-an-even-numbe/50653691).
> Small bug fix

- CONTRIBUTING.md
- Added link to notion
- Fixed minor typos
> Contributor doc

- components/Profile/ProfileCard.tsx
- styles/profile.ts
@FedericoCampe8 Merge the other PR first and I will rebase this after.
> Convert image to Avatar and resize margins, name and edit button

- components/Feed/Post/Post.tsx
> add cleanup function to use effect

- components/Feed/Comments/CommentEngagementBar.tsx
- components/Feed/Post/PostEngagementBar.tsx
- components/Feed/Replies/ReplyEngagementBar.tsx
- hooks/useOnCommentsPage.ts
- hooks/useUserHasLiked.ts
- lib/commentsHelper.ts
- lib/getLikesHelper.ts
- lib/repliesHelper.ts
- styles/feed.js
- Created a custom hook to track whether a user likes a post, comment or reply
- Added conditional styling so that the like button text color turns light red if the user has liked the post
- Also added conditional styling so that the comments button turns light purple (as though active) when on the comments page for that post
> track whether user has liked post and highlight like button

- components/Feed/Post/PostVotingMechanism.tsx
- styles/feed.js
- tailwind.config.js
Implemented the following except kept the current check mark rather than filled in circle
Also added highlight for current winning choice:
> Improve A vs B text  / image label UI

- components/Feed/Post/PostHeader.tsx
- firebase.js
- functions/index.js
- functions/package.json
Add a backend function and front-end code to delete comments (collections) recursively.
> Federico/dw 171/fix delete of posts wr

- components/Feed/Post/Post.tsx
- components/Feed/Post/PostVotingMechanism.tsx
> #25 - Feat: Allow author to view votes

- components/Header/ProfileButton.tsx
- components/Header/UserDropdown.tsx
- components/Utils/DropdownMenu.tsx
- styles/header.js
Fixed dropdown not closing by adding an imperative close call whenever a list item in the dropdown menu is clicked.
Branch: [Jira Ticket](https://oogwayai.atlassian.net/browse/OS-22?atlOrigin=eyJpIjoiMzcwZDA1YTliYTA3NDMyOTg0Y2Y0YTIyYzZmMDlkOWQiLCJwIjoiaiJ9)
> OS-22 Avatar dropdown does not close after my profile id is clocked

- components/Login/UserProfileForm.tsx
- package.json
- pages/api/auth/[...auth0].ts
- pages/api/auth/updateUser.ts
- pull_request_template.md
> #23 "Remove Image" not working in user profile

- .gitignore
- components/Feed/Comments/Comment.tsx
- components/Feed/Comments/CommentHeader.tsx
- components/Feed/Comments/CommentsAPI.tsx
- components/Feed/Forms/NewPostForm.tsx
- components/Feed/Post/Post.tsx
- components/Feed/Post/PostHeader.tsx
- components/Feed/Post/PostOptionsDropdown.tsx
- components/Feed/Post/PostsAPI.tsx
- components/Feed/Post/ToggleIncognito.tsx
- components/Feed/Replies/RepliesAPI.tsx
- components/Feed/Replies/Reply.tsx
- components/Feed/Replies/ReplyHeader.tsx
- components/Header/ToggleTheme.tsx
- hooks/needsHook.tsx
- lib/profileHelper.ts
- package.json
- pages/comments/[id].tsx
- pages/profile/[id].tsx
- styles/feed.js
- styles/header.js
- tsconfig.json
- utils/constants/global.ts
- utils/types/firebase.ts
- utils/types/params.ts
Branch: [OS-4-ability-to-create-anonymous-posts](https://github.com/EandrewJones/oogway-pilot/tree/OS-4-ability-to-create-anonymous-posts)
- Author label is shown for all posts (anon as well as non-anon) similar to Reddit's `OP` label.
- The UI for anonymous posts (author label and profile picture) is primitive for now. It could be made much better. Would like @EandrewJones's review and inputs on this. 
- Currently our app doesn't direct to author's profile on profile-pic-click in comments and replies. IMO that should be a separate PR.
Props to @EandrewJones for the initial UI work (#186)
> Os 4 ability to create anonymous posts

- components/Feed/Forms/NewPostForm.tsx
- utils/helpers/common.ts
JIRA Issue: https://oogwayai.atlassian.net/browse/OS-5?atlOrigin=eyJpIjoiZTZkY2JkZTdkNWUzNGE3ZWExNDU1NzA4MGUxOGE4ZGMiLCJwIjoiaiJ9
> OS#05 added support for Amazon URL

- components/Feed/Forms/NewPostForm.tsx
> OS-67: Change Warning text

- components/Feed/Comments/Comment.tsx
- components/Feed/Post/Post.tsx
- components/Feed/Post/PostVotingMechanism.tsx
- components/Feed/Post/PostsAPI.tsx
- components/Feed/Replies/Reply.tsx
- components/Utils/PreviewDecider.tsx
- pages/comments/[id].tsx
- pages/profile/[id].tsx
> OS-27: added preview support for comment and reply.

- components/Feed/Comments/Comment.tsx
- components/Feed/Comments/CommentsAPI.tsx
- components/Feed/Forms/NewReplyForm.tsx
- components/Feed/Replies/RepliesAPI.tsx
- components/Utils/Modal.tsx
- styles/feed.js
- styles/header.js
> OS-11: optimize app for mobile

- components/Feed/Replies/ReplyHeader.tsx
- lib/profileHelper.ts
JIRA Issue: https://oogwayai.atlassian.net/browse/OS-93
1. Removes the strange GET request noticed in console.
2. Fixes the author label for replies.
> Fix: anonymous post bugs

- components/Feed/Forms/Compare/_ComparePreview.tsx
- components/Feed/Forms/NewPostForm.tsx
- components/Utils/common/Avatar.tsx
- pages/profile/[id].tsx
- styles/feed.js
> OS-103 mobile view new post button is missing from my profile

- components/Feed/Forms/Compare/_ComparePreview.tsx
- components/Feed/Forms/NewCommentForm.tsx
- components/Utils/common/Avatar.tsx
-   [x] I have pulled the latest code from master and merged it into this branch
-   [x] I committed and pushed all my local code to this branch
> OS-84 fixed issue with image not uploading.

- components/Feed/Comments/Comment.tsx
- components/Feed/Post/Post.tsx
- components/Feed/Post/PostVotingMechanism.tsx
- components/Feed/Replies/Reply.tsx
- components/Utils/ErrorBoundary.tsx
- components/Utils/PreviewDecider.tsx
- pages/api/fetchPreviewData.ts
> OS-101 fixed issue with broken URL and crashing comments

- package.json
- pages/_app.tsx
> OS-108 install hotjar

- components/Feed/Comments/CommentHeader.tsx
- components/Feed/Comments/CommentsAPI.tsx
- components/Feed/Forms/NewReplyForm.tsx
- components/Feed/Replies/ReplyHeader.tsx
> OS 113 clicking avatar from comments does not open user profile

- components/Feed/Post/Post.tsx
- components/Feed/Post/PostVotingMechanism.tsx
- components/Utils/DropdownMenu.tsx
- pull_request_template.md
- styles/feed.js
- styles/globals.css
- utils/helpers/common.ts
> OS-29 css for fitting images.

- package.json
- pages/_app.tsx
- pages/_document.tsx
> OS 118 - added hotjar

- components/Feed/Sidebar/FeedPostbar.tsx
- components/Forms/NewPostForm.tsx
- hooks/useFeedOptions.ts
-   [ ] [General should be the first category in the select field]
-   [ ] [Post button should be disabled when there is not selected category and title of the question is empty]
> OS-118 changes to newPostForm

- pages/api/auth/[...auth0].ts
-   Login
-  Login auth cancel
> Yosgi/os 96/redirect user back to home page wh

- components/Decision/DecisionBarHandler.tsx
- components/Decision/DecisionSideBar.tsx
- components/Decision/DecisionTabWrapper.tsx
- components/Decision/OptionRatingTabWrapper.tsx
- components/Decision/OptionSlider.tsx
- components/Decision/ResultCard.tsx
- components/Decision/Sidecards/CriteriaSuggestions.tsx
- components/Decision/Sidecards/DecisionInfo.tsx
- components/Decision/Sidecards/OptionSuggestions.tsx
- components/Decision/Sidecards/SignInCard.tsx
- components/Decision/Sidecards/SuggestionItem.tsx
- components/Decision/Tabs/CriteriaTab.tsx
- components/Decision/Tabs/OptionTab.tsx
- components/Decision/Tabs/RatingTab.tsx
- components/Decision/Tabs/ResultTab.tsx
- components/Utils/ErrorWraperField.tsx
- features/decision/decisionSlice.ts
- features/interfaces.ts
- features/store.ts
- features/utils/utilsSlice.ts
- package.json
- pages/api/getAISuggestions.ts
- pages/decisionengine.tsx
- styles/decision.ts
- styles/login.js
- styles/utils.js
- tsconfig.json
- utils/helpers/common.ts
- utils/types/global.ts
> OS-126: AI suggestions

- .gitignore
- axios.js
- components/Feed/Comments/CommentEngagementBar.tsx
- components/Feed/Comments/CommentsAPI.tsx
- components/Feed/Post/PostsAPI.tsx
- components/Feed/Sidebar/FeedPostbar.tsx
- components/Forms/NewPostForm.tsx
- env/serviceAccount.enc.js
- lib/jwt/jwt.ts
- lib/upstash/rateLimit.ts
- next.config.js
- pages/api/ai/adviceBot.ts
- pages/api/auth/[...auth0].ts
- pages/api/decrypt.ts
- utils/constants/global.ts
- utils/helpers/decryptAES.ts
I have moved many of the new environment variables into an encryption-decryption approach to work around the 4kb limit Amazon lambda function restrictions place on Vercel.
See: [https://vercel.com/support/articles/how-do-i-workaround-vercel-s-4-kb-environment-variables-limit](https://vercel.com/support/articles/how-do-i-workaround-vercel-s-4-kb-environment-variables-limit)
All new environment variables should follow this approach. In fact, environment variables is misnomer because these no longer need to be added to the local env file nor Vercel's environment variables. Instead, you must follow the workflow below:
1. Store related variables in a common JSON object and add it to `envVars.json` (to be circulated privately) with a proper nested namespace. For example:
```
{ …
```
> Os 144 4 kb environment variable work around

- components/Decision/Sidecards/CriteriaSuggestions.tsx
- components/Decision/Sidecards/OptionSuggestions.tsx
- components/Decision/Sidecards/SignInCard.tsx
- components/Decision/Tabs/CriteriaTab.tsx
- components/Decision/Tabs/DecisionTab.tsx
- components/Decision/Tabs/OptionTab.tsx
- components/Decision/Tabs/RatingTab.tsx
- components/Decision/Tabs/ResultTab.tsx
- components/Decision/common/OptionSlider.tsx
- components/Decision/common/RatingSlider.tsx
- components/Decision/common/ResultCard.tsx
- components/Decision/common/SuggestionItem.tsx
- components/Decision/layout/DecisionBarHandler.tsx
- components/Decision/layout/DecisionSideBar.tsx
- components/Decision/layout/DecisionTabWrapper.tsx
- components/Decision/layout/OptionRatingTabWrapper.tsx
- features/decision/decisionSlice.ts
- features/interfaces.ts
- pages/decisionengine.tsx
- styles/decision.ts
- styles/globals.css
> OS-146 review changes

- components/Decision/layout/DecisionSideBar.tsx
- hooks/useMediaQuery.ts
> mobile hot fix

- components/Decision/layout/DecisionBarHandler.tsx
> update error text

- components/Decision/Sidecards/CriteriaInfo.tsx
- components/Decision/common/AISidebar.tsx
- pages/api/cacheDecisionCriteriaInfo/[id].ts
- queries/decisionCriteriaInfo.ts
- utils/types/firebase.ts
- utils/types/googleapi.ts
Front end checks whether cached results exists in firebase, if so they return those. Otherwise, they hit the API, cache the results in firebase and store them directly in the react-query query (triggers render on screeen). 
Query results are cached in memory and considered fresh for about ~30 mins. After that period expires, react query will refetch new results on button click following same order of operations above.
-   [ ] Criteria info is only displayed when user clicks asks AI button
-   [ ] Previously fetched results are not refetched if < 30 mins has passed (instantly render).
-   [x] I have created this PR through the following …
> working criteria information links

- components/Decision/Tabs/RatingTab.tsx
- components/Decision/common/RatingSlider.tsx
- components/Decision/layout/DecisionBarHandler.tsx
- components/Decision/layout/DecisionTabWrapper.tsx
- components/Decision/layout/OptionRatingTabWrapper.tsx
- styles/decision.ts
-   [x] [Check new design according to figma]
-   [x] [Check if on rating tab, when are the tabs are visited by the continue button it moves to result.]
> OS-154 New tab design

- pages/_document.tsx
-   [ ] [Check if the GA are connected and working correctly.]
> OS-156 Added GA

- pages/_app.tsx
- pages/_document.tsx
> OS-156 re-worked GA

- pages/decisionengine/index.tsx
Tiny change; shouldn't need review.
> change decision engine meta title

- components/Decision/Sidecards/CriteriaInfo.tsx
- components/Decision/Sidecards/CriteriaSuggestions.tsx
- components/Decision/Sidecards/OptionSuggestions.tsx
- components/Decision/common/AISidebar.tsx
- components/Decision/common/GenericSidebar.tsx
- pages/decisionengine/index.tsx
simple fix; no comments needed.
> disclaimer added

- components/Decision/Tabs/DecisionTab.tsx
- components/Decision/Tabs/RatingTab.tsx
- components/Decision/Tabs/ResultTab.tsx
- components/Decision/common/CriteriaSelectTabs.tsx
- features/decision/decisionSlice.ts
- features/interfaces.ts
- pages/api/decisionActivity.ts
- pages/decisionengine/index.tsx
- utils/types/firebase.ts
- instantiate new decisions in firebase when question changes
- update logs witth changes
- only create new decisions when question changes.
> OS 148 Imporove the way user decisions are logged

- lib/userHelper.ts
- utils/types/firebase.ts
Step that i followed:
- Delete the user from Firebase (from user and profile Document)
- Deleted the user from Auth0 dashboard.
- Created new user with and google.
- Created new user from Auth0 sign-up.
> OS-168 AuthFIx

- pages/decisionengine/index.tsx
> Os 170 fix scroll for mobile

- components/Decision/Sidecards/SignInCard.tsx
- components/Decision/Tabs/CriteriaTab.tsx
- components/Decision/Tabs/OptionTab.tsx
- components/Decision/common/CriteriaSelectTabs.tsx
- components/Decision/common/RatingSlider.tsx
- components/Decision/layout/DecisionBarHandler.tsx
- pages/decisionengine/index.tsx
- styles/globals.css
- styles/login.js
> OS-159 hide ai sidebar widgets from unauthenticated users

- components/Decision/Sidecards/CriteriaSuggestions.tsx
- components/Decision/Sidecards/OptionSuggestions.tsx
- components/Decision/Sidecards/SignInCard.tsx
- components/Decision/common/RatingSlider.tsx
- components/Decision/common/SuggestionItem.tsx
- features/decision/decisionSlice.ts
- styles/decision.ts
> OS-177/OS-163/OS-165 Small Bugs fixes

- pages/_document.tsx
> OS-182: Added Google tag manager

- components/Decision/Sidecards/SignInCard.tsx
- components/Decision/Tabs/DecisionTab.tsx
- components/Decision/Tabs/ResultTab.tsx
- components/Decision/common/RatingSlider.tsx
- components/Decision/layout/DecisionBarHandler.tsx
- features/decision/decisionSlice.ts
- features/interfaces.ts
- pages/api/unauthenticatedDecisions/[id].ts
- pages/api/unauthenticatedDecisions/index.ts
- pages/index.tsx
- queries/unauthenticatedDecisions.ts
- utils/constants/global.ts
- utils/types/firebase.ts
See [Jira Ticket](https://oogwayai.atlassian.net/browse/OS-192?atlOrigin=eyJpIjoiMzViZDk3OWJkNzgwNGQ4NzgyMmViZTc5NTZkMTllNzYiLCJwIjoiaiJ9)
> Restriction for AI features for unauthenticated users

- components/Decision/Tabs/DecisionTab.tsx
- components/Decision/Tabs/RatingTab.tsx
- components/Decision/Tabs/ResultTab.tsx
- components/Decision/common/AskAIButton.tsx
- components/Decision/common/CriteriaSelectTabs.tsx
- components/Decision/common/RatingSelector.tsx
- components/Decision/common/RatingSlider.tsx
- components/Decision/common/SuggestionItem.tsx
- components/Decision/layout/DecisionBarHandler.tsx
- components/Decision/layout/DecisionSideBar.tsx
- components/Decision/layout/DecisionTabWrapper.tsx
- components/Decision/layout/OptionRatingTabWrapper.tsx
- components/Utils/Button.tsx
- components/Utils/common/ProgressBar.tsx
- features/decision/decisionSlice.ts
- features/interfaces.ts
- pages/index.tsx
- styles/decision.ts
- styles/typography.ts
- styles/utils.js
- utils/constants/global.ts
- utils/helpers/common.ts
- utils/types/global.ts
> OS-158/OS-136: update rating tab and sidebar design

- components/Decision/Tabs/DecisionTab.tsx
-   [x] [Criteria 1]
-   [x] [Criteria 2]
-   [x] [Area 1]
-   [x] [Area 2]
> preventDefaultOnEnter added to onkeyPress for question field

- components/Decision/SideCards/SignInCard.tsx
- components/Decision/Tabs/CriteriaTab.tsx
- components/Decision/Tabs/DecisionTab.tsx
- components/Decision/Tabs/OptionTab.tsx
- components/Decision/Tabs/RatingTab.tsx
- components/Decision/Tabs/ResultTab.tsx
- features/decision/decisionSlice.ts
- hooks/useInstantiateDecisionForm.tsx
- pages/index.tsx
> fix global state bugs

- pages/_document.tsx
> Added envrinment changes

- pages/_document.tsx
> OS-206-install-adsense-code

- components/Decision/Tabs/CriteriaTab.tsx
- components/Decision/Tabs/MatrixResultTab.tsx
- components/Decision/common/CriteriaSelectTabs.tsx
- features/decision/decisionSlice.ts
- pages/_app.tsx
- pages/_document.tsx
> OS-219: Criteria changes

- components/Decision/layout/DecisionTabWrapper.tsx
- components/Utils/Modal.tsx
- features/decision/decisionSlice.ts
- features/interfaces.ts
- pages/index.tsx
- utils/constants/global.ts
> OS-175: add-explanation-for-each-tab

- components/Decision/Tabs/DecisionTab.tsx
> OS-239: showing-a-tie-result-for-a-clear-winner

- components/Decision/SideCards/SignInCard.tsx
- components/Decision/Tabs/DecisionTab.tsx
- components/Decision/Tabs/MatrixResultTab.tsx
- components/Decision/Tabs/ResultTab.tsx
> OS-238: ux-updates

- components/Decision/common/ResultTable.tsx
- components/Layout.tsx
- components/Utils/Tooltip.tsx
- lib/userHelper.ts
- utils/types/firebase.ts
- utils/types/global.ts
> OS-247: Added tooltip to table header
